name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Copy version files
        shell: bash
        run: |
          cp curl/src/main/native/config/versions/nghttp2ver.h curl/src/main/native/nghttp2/lib/includes/nghttp2/nghttp2ver.h
          cp curl/src/main/native/config/versions/nghttp3ver.h curl/src/main/native/nghttp3/lib/includes/nghttp3/version.h
          cp curl/src/main/native/config/versions/ngtcp2ver.h curl/src/main/native/ngtcp2/lib/includes/ngtcp2/version.h
          echo "#include \"tool_hugehelp.h\"" > curl/src/main/native/curl/src/tool_hugehelp.c
      - name: Configuration Environment
        shell: bash
        run: |
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          ./gradlew :t:assemble
          ./gradlew :c:publishToMavenLocal
          ./gradlew :c:publishToMavenLocal -PenableLTO=1
      - name: Upload app
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: tool/build/outputs
          compression-level: 9
      - name: Upload library
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: ~/.m2
          compression-level: 9
          include-hidden-files: true
